- ruby/2.5.1-node-chrome/Dockerfile
This PR adds a really basic Ruby image with node and chrome for either testing on Circle or deployment on our k8s cloud. I've chosen a folder structure where ruby is the folder and the tag includes the version and "extras" included. In the future, I see our other ruby images going here.
The motivation for this work was https://github.com/artsy/bearden/pull/347 where I was trying to upgrade to the latest Ruby. I was blocked because I was dependent on Circle and their upgrade schedule. In order to upgrade Ruby to 2.5.1, I had to wait until they updated their images. Making our own puts us back in control there.
> Add Ruby image with node and chrome

- scala/Dockerfile
We need this for testing for when the pg database image is available, using `psql`.
> add postgresql-client

- elixir/Dockerfile
I've already pushed this to https://hub.docker.com/r/artsy/elixir/.
Some recent libraries weren't compiling without bringing back in a full Erlang installation.
> elixir 1.6.6 base image

- goreplay/Dockerfile
Build from source as file rotation is not working properly in release 1.16.1 and we need https://github.com/buger/goreplay/pull/477 which is only in master.
Took build steps and flags from https://github.com/buger/goreplay/blob/master/Makefile and set version to 1.16.2-alpha
> build goreplay from source

- volt-testing/Dockerfile
While going through the process of getting Volt on Circle CI 2.0, I made an image that includes qt.
> Add image for testing Volt on CircleCI

- graalvm/Dockerfile
I already pushed this to https://hub.docker.com/r/artsy/graalvm/.
cc @erikdstock @javamonn
> update graalvm to 1.0.0-rc8

- ruby/2.3.3-node-chrome/Dockerfile
I already pushed the image [here](https://hub.docker.com/r/artsy/ruby/tags/) and it's used by https://github.com/artsy/ohm/pull/471.
> Add ruby:2.3.3-node-chrome

- graalvm/Dockerfile
- scala/Dockerfile
- scala/graalvm/Dockerfile
I already pushed these to docker hub.
I tagged the new non-GraalVM image as `artsy/scala:2.12.7-node`.
cc @erikdstock @javamonn
> Add dockerizer, update scala version

- ruby/2.6.1-node-chrome/Dockerfile
I've been lax in my addition of new Ruby images, so this PR adds 2.6.1 while I wait for the official 2.6.2 to land. These PRs are weird - by the time I've opened this the new image is actually already pushed to DockerHub. 🤷‍♂️
> Add Ruby 2.6.1 node chrome

- elasticsearch/5.6/Dockerfile
- elasticsearch/5.6/es-wrapper.sh
Noticing that the cluster goes to a "red" state while rotating nodes, due to failures to sync cluster state.  This is caused by the pod's network interface being deleted before other nodes in the cluster can detect it as down.
This issue is detailed in https://discuss.elastic.co/t/timed-out-waiting-for-all-nodes-to-process-published-state-and-cluster-unavailability/138590 and https://github.com/elastic/helm-charts/issues/63
As a workaround, adopted a pattern from https://github.com/qoqodev/elasticsearch-hooks-docker to wait for 10 seconds after shutting down the Elasticsearch process before exiting, so other nodes have time to detect the terminating node, re-elect a new master and sync cluster state.
> add elasticsearch wrapper to delay shutdown

- scala/scala-2.12/Dockerfile
- scala/scala-2.12/Dockerfile.node
- scala/scala-2.12/README.md
- scala/scala-2.12/build.sh
We're trying out the latest Corretto version (11). They now have an official image based on Amazon Linux.
I have already pushed these to [Docker Hub](https://cloud.docker.com/u/artsy/repository/docker/artsy/scala).
I'll do some cleanup of Java/Scala directories once we know this works OK.
> Scala 2.12.8 images based on Amazon Corretto

- pg-data-sync/export-db.sh
- pg-data-sync/import-db.sh
This script was failing when triggered in Kubernetes with the following error:
This PR removes second argument to `export-db` script, which matches it to a functional, existing dump script here: https://github.com/artsy/galaxy-api/blob/master/data-sync/export-db.sh#L6
I was able to run the script locally and get a successful pg archive.
> Remove ambiguous arg

- pg-data-sync/Dockerfile
- pg-data-sync/README.md
- pg-data-sync/export-db.sh
- pg-data-sync/import-db.sh
- Fix overriding pg_dump and pg_restore args as a second argument provided to scripts.
- Downgrade to v9.5 of the tools... this should fix `could not execute query: ERROR:  unrecognized configuration parameter "idle_in_transaction_session_timeout"` errors on restore  (Perhaps we should maintain separate tags going forward, but for our uses this should work with our RDS databases...)  
- Add the flag `--schema=public` to the default `pg_restore` args - this should fix all erros trying to drop / recreate or modify the public schema on restore.
> Update pg data sync

- sidekiq-migrate/Dockerfile
- sidekiq-migrate/README.md
- sidekiq-migrate/migrate.rb
Script to migrate Sidekiq queues from one Redis to another.
I sourced the idea from https://github.com/mperham/sidekiq/issues/3900#issuecomment-410104469 then refactored a bit.
My first try migrating Convection staging, all scheduled jobs were executed immediately.  So I dropped the Sidekiq dependency in the source code, and dropped down a level to migrate everything using only Redis commands.
Also refactored so that keys remain in place in the old Redis, unless CLEAN_UP is supplied.
After testing importing to my local Redis, I felt bold, and ran the import on Convection production, knowing that without setting `CLEAN_UP=true` I could retry if anything went wrong.  But it didn't!  And you can now see all retry / scheduled jobs that were on our previous Redis instance in …
> add sidekiq-migrate

- redis-migrate/Dockerfile
- redis-migrate/README.md
- redis-migrate/migrate.py
Docker image to migrate all keys in Redis database as AWS Elasticache Redis deployments [don't allow](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html) using the Redis [MIGRATE command](https://redis.io/commands/migrate)
> Redis migrate

- mongo-data-sync/Dockerfile
- mongo-data-sync/README.md
- mongo-data-sync/export-db.sh
- mongo-data-sync/import-db.sh
- pg-data-sync/import-db.sh
Dockerizes the Mongo db sync used by Positron, so we can reuse on other db's and easily reference preferred strategy in docs. 
This PR updates the existing script from Positron to more closely match the error handling in the PG equivalent-- for example telling you if an env var is missing.
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-2223
> Dockerize Mongo db-sync

- redis-migrate/README.md
- redis-migrate/migrate.py
Trying to make this more consistent with out apps' connection string / sidekiq-migrate parameters and options
Also I encountered an error migrating Volt production:
```
Traceback (most recent call last):
File "/migrate.py", line 71, in <module>
run()
File "/migrate.py", line 68, in run
migrate_redis(options.source, options.destination)
File "/migrate.py", line 55, in migrate_redis
dst.restore(key, ttl * 1000, value, replace=REPLACE_DST_KEYS)
File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1487, in restore
return self.execute_command('RESTORE', *params)
File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 838, in execute_command
conn.send_command(*args)
File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 686, in send_command …
```
> Updates to Redis migrate

- pg-data-sync/export-db.sh
- pg-data-sync/import-db.sh
Add verbose output by default and introduce the `SWALLOW_ERRORS_ON_RESTORE` env var so a Kubernetes job running a 1-off pod import, for instance, exits cleanly
> Update pg-data-sync images

- pg-data-sync/.gitignore
- pg-data-sync/Dockerfile
- pg-data-sync/build.sh
- pg-data-sync/export-db.sh
- pg-data-sync/import-db.sh
- Update pg-data-sync to generate Dockerfiles for Postgres versions 9-12 and publish to ECR
- Add option to specify `USE_ARCHIVE_TIMESTAMP` so as to generate a specific point-in-time archive and save to S3 (this can be passed into the restore script)
- Update scripts to save archive file to /tmp so we can attach a persistent volume when generating or restoring large backups
> generate Docker images for Postgres versions 9-12 

- ruby/2.7.1-node-chrome/Dockerfile
Not much to see here, just a copy/paste from the 2.7.0 Dockerfile to bump the patch-level of Ruby.
> Add image for Ruby 2.7.1

- pg-data-sync/import-db.sh
`exit $?` in the `if` statement at the end just returns the result of the if (0 if true, 1 if not). I think the intention is to return the exit code of pg_restore.
this possibly explains this jenkins job's failed status:
https://joe.artsy.net/job/gravity-staging-weekly-cron2/15/console
Migration
---
Update docker image.
> #MIGRATON fix: catch pg_restore exit code to use at the end.

- pg-data-sync/build.sh
- pg-data-sync/export-db.sh
- pg-data-sync/import-db.sh
https://artsyproduct.atlassian.net/browse/PLATFORM-3059
https://joe.artsy.net/job/gravity-staging-weekly-cron2/15/console
The log is flooded with aws s3 cp's progress output:
```
Completed 471.8 MiB/553.0 MiB with 1 file(s) remaining
Completed 472.0 MiB/553.0 MiB with 1 file(s) remaining
```
Loading full log and searching through it (on Jenkins UI) takes a while I think b/c of so many of those lines. Suggest to suppress that output by adding `--no-progress` flag to aws s3 cp. To retain timing and size info, adding `ls` and separate timestamp for s3 download/upload.
If merged I will run ./build.sh to push up new images to dockerhub.
Related PR: https://github.com/artsy/gravity/pull/13747
> feat: reduce verbosity of pg-data-sync output.

- jenkins-master/Dockerfile
- jenkins-master/build.sh
https://artsyproduct.atlassian.net/browse/PLATFORM-3257
relates to:
https://github.com/artsy/substance/pull/244
https://github.com/artsy/infrastructure/pull/298
I created `artsy/jenkins-master` dockerhub repo and made it Public.
`build.sh` pushes image to that repo and i already did.
> feat: jenkins master docker build.

- ruby/2.6.6-node-14-yarn/Dockerfile
The `artsy/node` v2 orb [uses node 14](https://github.com/artsy/orbs/commit/5cdcdd95fb7b927127f5f8b9a4efec4216fd8a27); we needed a new docker image [to get volt to work with this orb](https://github.com/artsy/volt/pull/5276/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L1), since it was previously using node 12. This is that image!
It's already been pushed to docker hub.
> feat: new image for ruby, node 14, yarn

- ruby/2.5.3-node-chrome/Dockerfile
- ruby/2.6.5-node-chrome/Dockerfile
https://artsyproduct.atlassian.net/browse/PLATFORM-3637
https://artsy.slack.com/archives/CP9P4KR35/p1633017320060100
[Ohm](https://app.circleci.com/pipelines/github/artsy/ohm/946/workflows/a3f75999-0097-43d7-af60-8dc1e527e9b5/jobs/1467) and [Currents](https://app.circleci.com/pipelines/github/artsy/currents/1493/workflows/ae61a4ca-735d-4169-9d02-67bc92b216c6/jobs/2202) builds are failing on nodesource due to [expired](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) CA cert `DST Root CA X3`.
Tried bunch of potential work-arounds. This PR adopts [this workaround](https://github.com/nodesource/distributions/issues/1266#issuecomment-933228467) as it seems the only one that works across Debian versions.
Implement this for only two artsy images because the others are …
> fix: work around expired ca cert

- pg-data-sync/import-db.sh
[PLATFORM-3737] 
When running pg_restore with `-c`/`--clean` option, we want to also specify `--if-exists`, otherwise error messages are raised in case the destination database does not contain any objects
For reference, see:
https://www.postgresql.org/docs/12/app-pgdump.html
[PLATFORM-3737]: https://artsyproduct.atlassian.net/browse/PLATFORM-3737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PLATFORM-3737]  Prevent pg_restore from raising error unnecessary errors

- mongo-data-sync/Dockerfile
https://artsyproduct.atlassian.net/browse/PLATFORM-3902
Staging mongo atlas cluster is at `4.2`. Production cluster is still at `4.0` but will be upgraded to `4.2` soon.
Bump the image here to `4.2` which I hope is (and it should be) backward compatible with `4.0` cluster.
This image is used by Kaws and Positron data-sync k8s cronjobs which pull the `latest` tag.
Migration (applied)
---
```
cd ./mongo-data-sync
docker build . -t artsy/mongo-data-sync:4.2
docker push artsy/mongo-data-sync:4.2
docker tag artsy/mongo-data-sync:4.2 artsy/mongo-data-sync:latest
docker push artsy/mongo-data-sync:latest
```
> [MIGRATION] feat: advance mongo client version to 4.2

- mongo-data-sync/Dockerfile
like https://github.com/artsy/docker-images/pull/87, but for 4.4
production cluster has been upgraded to 4.4
Migration (applied)
---
```
cd ./mongo-data-sync
docker build . -t artsy/mongo-data-sync:4.4
docker push artsy/mongo-data-sync:4.4
docker tag artsy/mongo-data-sync:4.4 artsy/mongo-data-sync:latest
docker push artsy/mongo-data-sync:latest
```
> [MIGRATION] feat: advance mongo client version to 4.4

- ruby/2.7.3-node-chrome/Dockerfile
Cuts a new `ruby` 2.7.3 version, with `node`.
This should solve some of the [noisy output problems](https://github.com/DataDog/dd-trace-rb/issues/1542#issuecomment-854463079) afflicting some apps running against ruby 2.7.1 
(I would have liked to bump all the way up to 2.7.6, but when I tried to do so I got cryptic errors about `npm` not being found 🤷🏽 )
> feat: add ruby 2.7.3-node-chrome

- detect-secrets/Dockerfile
This bumps the version to latest release.
[New tags already pushed](https://hub.docker.com/r/artsy/detect-secrets/tags).
> chore: bump detect-secrets to v1.3.0

- ruby/2.7.3-node-14-chrome/Dockerfile
Lil follow up to #91 that cuts a new version using Node 14 instead of the EOL Node 10.
> feat: add ruby:2.7.3-node-14-chrome

- ruby/3.0.2-node-16-yarn/Dockerfile
In support of bumping Node in Volt, this adds a new ruby docker image and bumps node to 16.18.0.
> feat(ruby): Add ruby+node-v16.18.0 image

- .circleci/config.yml
- README.md
- detect-secrets/Dockerfile
- detect-secrets/README.md
- detect-secrets/build
- detect-secrets/continue_config.yml
- detect-secrets/push
https://artsyproduct.atlassian.net/browse/PLATFORM-4643
This introduces CI pipeline for building and releasing new versions of Artsy `detect-secrets` docker image.
~See the [Upgrade and Release](https://github.com/artsy/docker-images/blob/1138db4eba4ec638c917cd2352f4720500a338c4/detect-secrets/README.md#upgrade-and-release) section for how the process is setup.~
~As described the release trigger is two-fold:~
~- '_detect-secrets_' must be included in the branch name for the workflow to run~
~- a '_hold_' mechanism is in place to allow for more controlled release: in case a follow-up change needs to be made or to wait for a PR approval etc...~
---
This PR has been heavily adjusted following feedback. See [this comment](https://github.com/artsy/docker-images/pull/96#issuecomment-1382507994). …
> feat: detect-secrets CI

- README.md
Building on apple silicon will result in the wrong architecture, as caught by @jpotts244 (see below screenshot, OS/ARCH is set to linux/amd64/v8).
Using the `--platform linux/amd64` parameter ensures we're only building images on linux/amd64
> chore: update README to include instructions to build in amd64

- ruby/3.0.2-node-14-yarn/Dockerfile
This bumps alpine version to 3.14 (from 3.13).
The primary motivation is to allow us to use a more recent version of python, 3.9+, in [horizon](https://github.com/artsy/horizon) so that latest version of hokusai can be installed which depends on python >=3.9. Highest version of python available in [alpine3.13 is 3.8.15](https://pkgs.alpinelinux.org/packages?name=python3&branch=v3.13&repo=&arch=&maintainer=).
This image is also used in [gravity](https://github.com/artsy/gravity/blob/main/Dockerfile#L2). Local build succeded using this new base.
Related [slack thread](https://artsy.slack.com/archives/CA8SANW3W/p1691420429917559).
> chore: bump alpine to 3.14 for ruby:3.0.2-node-14-yarn

- pg-data-sync/.gitignore
- pg-data-sync/Dockerfile
- pg-data-sync/Makefile
Follow-up to https://github.com/artsy/docker-images/pull/103
- remove `.gitignore` as that is no longer needed following #103
- remove outdated comments
- rename make targets
- fix `publish-hub` build command
> refactor: pg-data-sync build

- elasticsearch/6.8.23/README.md
- elasticsearch/6.8.23/amd64/Dockerfile
- elasticsearch/6.8.23/amd64/elasticsearch.yml
- elasticsearch/6.8.23/arm64/Dockerfile
- elasticsearch/6.8.23/arm64/elasticsearch.yml
https://artsyproduct.atlassian.net/browse/PHIRE-393
This supports the [local development](https://artsyproduct.atlassian.net/browse/PHIRE-330) effort.
Immediately after starting work on the gravity local dev stack, it became evident that running the `amd64` architecture Elasticsearch `v6.8.23` image is problematic. The service would not start up consistently, there were errors in the logs requiring additional Elasticsearch configuration to be enabled as well as obvious performance issues that made the experience worse.
> Official Elasticsearch `arm64` support starts with [v7.8.0](https://www.elastic.co/blog/elasticsearch-on-arm).
This PR introduces _two_ custom Elasticsearch images, one for `amd64` and one for `arm64` so that a docker manifest can be created and made available for local …
> chore: multi-arch Elasticsearch v6.8.23 image

- ruby/3.1.4-node-18-yarn/Dockerfile
Adding 3.1.4 image
[Uploaded to docker hub](https://hub.docker.com/layers/artsy/ruby/3.1.4-node-18-yarn/images/sha256-63811e95d916f2c972314fa2413e8279fc19459b4f6452882c691ef3d53e5a07?context=explore)
[Working in Pulse](https://app.circleci.com/pipelines/github/artsy/pulse?branch=leamotta%2Fruby-3.1)
> chore: ruby 3.1.4

- detect-secrets/Dockerfile
detect-secrets `v1.5.0` has been [released](https://github.com/Yelp/detect-secrets/releases/tag/v1.5.0) and just landed in [homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/d/detect-secrets.rb). This bumps the version so CI wont be [blowing up](https://app.circleci.com/pipelines/github/artsy/gravity/28469/workflows/fef6418f-4b4a-48e3-86b6-26f97649fb75/jobs/52826) when users push version change of the `.secrets.baseline`.
> chore: bump detect-secrets version to 1.5.0

- mongo-data-sync/Dockerfile
- mongo-data-sync/load-secrets-and-run.sh
- pg-data-sync/Dockerfile
- pg-data-sync/load-secrets-and-run.sh
This PR adds the `load-secrets-and-run.sh` script to our `mongo-data-sync` and `pg-data-sync` `docker` images. This allows the image to support our `vault` setup and load secrets into their containers without the use of `ConfigMaps` to [store shared scripts](https://github.com/artsy/positron/pull/3165). 
While we could potentially import a shared script from outside each's directory, I opted to keep all parts of the build process located within the respective `Dockerfile` context. 
Follow the `README` [instructions](https://artsyproduct.atlassian.net/browse/PHIRE-1419), to rebuild and push the updated image to our docker-hub.
[PHIRE-1419]
[PHIRE-1419]: https://artsyproduct.atlassian.net/browse/PHIRE-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> chore: add load-secrets-and-run.sh to mongo and pg data sync images

- pg-data-sync/Dockerfile
- pg-data-sync/Makefile
- pg-data-sync/export-db.sh
https://artsyproduct.atlassian.net/browse/PHIRE-1637
Prepares for rds gravity-production engine version bump
- Upgrade pg (data-sync) image version to match rds server version
Tags already pushed: [ecr](https://us-east-1.console.aws.amazon.com/ecr/repositories/private/585031190124/pg-data-sync?region=us-east-1), [hub](https://hub.docker.com/r/artsy/pg-data-sync/tags)
> chore: upgrade pg-data-sync database version

- pg-data-sync/export-db.sh
Switching the entrypoint to `load-secrets-and-run.sh` has caused an issue where each word split on whitespace [here](https://github.com/artsy/motion/blob/902fed7e8930670389b5ed544c08a96131327088/dags/gravity/data_sync/pipeline.py#L97-L99) is passed to `export-db.sh` as an individual arg. This means only `-O` has been passed to `pg_dump`, resulting in memory and disk issues. This fixes that issue by:
1. Checking that more than one arg was passed to `export-db.sh`
2. If there was, set `PG_DUMP_ARGS` as all args from the second onwards.
I tested this locally by running the following (taken from @ovasdi ):
```
docker build --platform linux/amd64 -f Dockerfile -t pg-data-sync:test .
docker run -it --platform linux/amd64 pg-data-sync:test ./export-db.sh foo "-O -Fc -v --schema=public …
```
> fix: pass all args from position 2 onwards to pg_dump

- pg-data-sync/export-db.sh
- pg-data-sync/import-db.sh
Follow-up to https://github.com/artsy/docker-images/pull/115
The weekly sync does not _currently_ pass additional args when running the [import](https://github.com/artsy/motion/blob/902fed7e8930670389b5ed544c08a96131327088/dags/gravity/data_sync/pipeline.py#L114-L116) but this could change in the future and then `pg_restore` would fail similarly as we saw last weekend. This copies the fix from related PR to the `import-db.sh` making is safe to pass additional arguments.
```sh
docker run -it ... pg-data-sync:test ./import-db.sh foo "--clean --if-exists --no-owner --no-privileges --schema=public -v"
...
Running command: ./import-db.sh foo --clean --if-exists --no-owner --no-privileges --schema=public -v
Using archive name: foo
...
[pg_restore] Running with args: --clean --if-exists …
```
> fix: pass all args from position 2 onwards to pg_restore

- fluentd/Dockerfile
- fluentd/build.sh
The [off-the-shelf FluentD image](https://github.com/artsy/substance/pull/410/files#diff-f93fd760ceb77a8c8a08c349dc4959c70857163eca34377686d138bdf7c0469bL78) does not include S3 plugin which is now required to support https://github.com/artsy/substance/pull/410.
So let's bake our own image to include S3 plugin.
I have already run `build.sh` which pushed new image to [Dockerhub](https://hub.docker.com/repository/docker/artsy/artsy-fluentd/general).
> feat: customize fluentd docker image for our use

- ruby/3.3.0-node-22-yarn/Dockerfile
Patches #119 to use the correct ruby version.
image already built and pushed.
> fix: use correct ruby version for node 22

- ruby/3.4.2-node-22-yarn/Dockerfile
For Volt upgrade to Ruby 3.4
https://hub.docker.com/layers/artsy/ruby/3.4.2-node-22-yarn/images/sha256-5152fb7f246bdba258c47ce271f0adaebddbe25f9182d7816544df1b178a4bb0
> chore: ruby 3.4 + node 22
