artsy/docker-images

- elasticsearch/Dockerfile
- elasticsearch/elasticsearch.yml
Configure with `script.inline: on` for our dev and test environments
> add elasticsearch

- scala/Dockerfile
I already ran:
```bash
docker build -t artsy/scala
docker push artsy/scala
```
so the image is updated on Docker Hub.
> Add awscli and jq for deploys

- graalvm/Dockerfile
- graalvm/README.md
- scala/graalvm/Dockerfile
- scala/graalvm/README.md
I already pushed these to Docker Hub. We're testing to see if this speeds up [Causality](https://github.com/artsy/causality)'s CI.
> Set up GraalVM and Scala/GraalVM images

- goreplay/Dockerfile
Base build to download and run goreplay with some extra goodies installed
> add goreplay build

- elixir/Dockerfile
- graalvm/Dockerfile
- graalvm/README.md
> switch from minideb to debian:stretch

- README.md
- ruby/2.5.3-node-chrome/Dockerfile
This PR adds a new image for Ruby 2.5.3 and then also updates the README so that I can remember how to update Docker Hub since I do this so infrequently. 😝
> Add new ruby version

- scala/Dockerfile
This is already on docker hub.
> add hokusai, update sbt version

- ruby/2.6.0-node-chrome/Dockerfile
Adds a basic Dockerfile for Ruby 2.6.0.
> Add basic Dockerfile for Ruby 2.6.0

- README.md
Just a small update to README including the docker login step!
> update README with login step

- ruby/2.6.2-node-chrome/Dockerfile
The main Ruby image landed so I'm just updating for the newest version here.
> Add Ruby 2.6.2 image

- pg-data-sync/Dockerfile
- pg-data-sync/README.md
- pg-data-sync/export-db.sh
- pg-data-sync/import-db.sh
A generic Postgres data-sync utility we can use with apps like Rosalind and Candela, and more!
> add pg-data-sync

- ruby/2.6.5-node-chrome/Dockerfile
Over the weekend I had a need for a newer Ruby image so I made one and pushed it so this is just a PR to add it to the repo.
> Add image for Ruby 2.6.5

- pg-data-sync/import-db.sh
Updates data-sync import script to make flags verbose (for easier legibility) and adds `--clean` flag. 
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-2046
> Data import uses --clean, add verbose flags

- sidekiq-migrate/Dockerfile
- sidekiq-migrate/migrate.rb
- Add option to migrate stats by setting `MIGRATE_STATS=true` (@joeyAghion I know you said it's probably not necessary but it was so easy to implement ;) )
- Fixes to Dockerfile CMD syntax
- Fixes to logging
> Fixes to sidekiq migrate

- sidekiq-migrate/README.md
- sidekiq-migrate/migrate.rb
As discussed in https://github.com/artsy/docker-images/pull/57 remove the `ACTUAL_RUN` and really run by default - replace with `DRY_RUN` env var.
Need  a sanity check on the changes to conditional statements!  `unless` continues to confound me.
Also migrate stats by default because it's so easy and simplifies things.
> Update Sidekiq migrate

- redis-migrate/README.md
Minor updates to readme to clarify how to run as dry-run, and how to ensure records are present.
> Add additional info on dry run and args

- sidekiq-migrate/README.md
Adds example run script and `DEBUG` env var.
> Clarify sidekiq migrate script

- ruby/2.7.0-node-chrome/Dockerfile
Not much to see here, just adding the image for Ruby 2.7.0.
> Add image for Ruby 2.7

- mongo-data-sync/Dockerfile
Building docker image failed because I incorrectly named the files in Dockerfile in #63.
> Fix file names for mongo sync

- pg-data-sync/import-db.sh
https://artsy.slack.com/archives/CA8SANW3W/p1610208344111000
- Fix typo.
- Also have script clearly echo source of exit code.
> fix: pg-data-sync import-db.sh typo.

- jenkins-master/Dockerfile
- jenkins-master/jenkins.sh
follows: https://github.com/artsy/docker-images/pull/77
relates to: https://github.com/artsy/substance/pull/245
> minor revision to jenkins dockerfile.

- ruby/2.6.8-node-14-yarn/Dockerfile
Only changing the ruby patch version: from 2.6.6 to 2.6.8
> Add image for Ruby 2.6.8

- ruby/3.0.2-node-14-yarn/Dockerfile
Add ruby 3 image, to be used for Volt upgrade to ruby 3
> feat: add ruby 3 image

- detect-secrets/Dockerfile
- detect-secrets/build
- detect-secrets/push
https://hub.docker.com/repository/docker/artsy/detect-secrets/tags?page=1&ordering=last_updated
testing 1.1.0 here (eigen is on 1.1.0 on that branch): https://app.circleci.com/pipelines/github/artsy/eigen/29360/workflows/2004dcdd-2c27-439d-952f-3040e90ed792/jobs/87699 from https://github.com/artsy/eigen/pull/6990
testing 1.2.0 here (eigen is on 1.2.0 on that branch): https://app.circleci.com/pipelines/github/artsy/eigen/29362/workflows/c5571d1b-cae3-4151-b028-ab59b7cafade/jobs/87706 from https://github.com/artsy/eigen/pull/6991
> add detect-secrets dockerfile

- ruby/2.7.6-node-12-yarn/Dockerfile
Needed for https://github.com/artsy/radiation/pull/829
Already built & pushed!
> feat: add ruby 2.7.6 node 12 image

- ruby/3.2.3-node-18-yarn/Dockerfile
> chore: ruby 3.2.3 image

- ruby/3.3.0-node-18-yarn/Dockerfile
> chore: ruby 3.3 image

- ruby/3.4.1-node-18-yarn/Dockerfile
> chore: ruby 3.4 image
